version: '3.8'

      services:
        backend:
          build:
            context: .
            dockerfile: Dockerfile
          ports:
            - "8000:8000"
          volumes:
            - ./backend:/app

        frontend:
          build:
            context: .
            dockerfile: frontend/Dockerfile
          ports:
            - "3000:3000"
          depends_on:
            - backend
          volumes:
            - ./frontend:/app
            - /app/node_modules